title: Wallop Vintage Gathering
description: Wallop vintage gathering website

url: "https://wallopvintagegathering.github.io"

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact
 - title: Visit
   url: /visit

social:
   email: tony@gaigerbros.co.uk